#pragma once

#include <nycedefs.h>

#define ROCKS_EXTERN_MASK								30

#define ROCKS_ERR_PU_RATE_ERROR							((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 0)))
#define ROCKS_ERR_DELTA_PARS_ERROR						((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 1)))
#define ROCKS_ERR_DELTA_TAJ_OVER_WORKSPACE				((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 2)))
#define ROCKS_ERR_DELTA_TAJ_VEL_ERROR					((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 3)))
#define ROCKS_ERR_DELTA_JOINT_POS_ERROR					((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 4)))
#define ROCKS_ERR_DELTA_POSTURE_ERROR					((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 5)))

#define ROCKS_ERR_MAX_ANGLE_ACCELERATION_EXCEEDED		((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 10)))
#define ROCKS_ERR_MAX_RADIAL_VELOCITY_EXCEEDED			((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 11)))
#define ROCKS_ERR_MAX_RADIAL_ACCELERATION_EXCEEDED		((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 12)))

#define ROCKS_ERR_READ_BELT_POS_FAIL					((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 13)))
#define ROCKS_ERR_CALC_CATCH_POS_FAIL					((NYCE_STATUS)((NYCE_ERROR_MASK)|(SS_ROCKS<<NYCE_SUBSYS_SHIFT)|(ROCKS_EXTERN_MASK + 14)))

#define ROCKS_MOVE_TYPE_SPIRAL							10
#define ROCKS_MOVE_TYPE_SPIRAL_EX						11